'use strict';
const $=id=>document.getElementById(id),game=$('game'),c=$('c'),ctx=c.getContext('2d');
const ui={score:$('score'),stage:$('stageHud'),rem:$('remaining'),coins:$('coins'),shop:$('shop'),shopCoins:$('shopCoins'),first:$('first'),stageCard:$('stageCard'),stageTitle:$('stageTitle'),stageSub:$('stageSub'),over:$('over'),win:$('win'),toast:$('toast'),joy:$('joy'),knob:$('knob'),fire:$('fire')};
const SAVE='jf-polished-v1';let save={coins:0,highScore:0,gender:null,owned:['basic'],equipped:'basic'};try{save={...save,...JSON.parse(localStorage.getItem(SAVE)||'{}')}}catch(_){}const persist=()=>{try{localStorage.setItem(SAVE,JSON.stringify(save))}catch(_){}};
const atlas=new Image();let spriteSource=atlas;atlas.src='assets/characters_atlas.png';const CELL=144;const stateCol={idle:0,run1:1,run2:2,run3:3,jump:4,crouch:5};
const TIME=.50,GRAV=1750,WORLD=12600;let W=390,H=844,DPR=1,ground=650,cam=0,last=performance.now(),clock=0,paused=false,started=!!save.gender,stage=1,score=0,spawned=0,defeated=0,spawnTimer=1.3,stageChanging=false,toastT=0,shake=0;
const bullets=[],enemyBullets=[],enemies=[],drops=[],fx=[];let roofs=[],stairs=[],doors=[],spawnPoints=[],buildings=[];
const stages={1:{mix:Array(5).fill('normal'),active:2,roof:.12,delay:[2.2,3.4],sub:'5 אויבים רגילים'},2:{mix:Array(7).fill('normal'),active:3,roof:.20,delay:[2.0,3.0],sub:'7 אויבים'},3:{mix:Array(7).fill('normal').concat(['heavy','heavy']),active:3,roof:.27,delay:[1.9,2.8],sub:'2 אויבים חזקים מצטרפים'},4:{mix:Array(7).fill('normal').concat(['fast','fast','heavy','heavy']),active:4,roof:.32,delay:[1.8,2.7],sub:'אויבים מהירים מצטרפים'},5:{mix:Array(7).fill('normal').concat(Array(3).fill('fast'),Array(3).fill('heavy')),active:4,roof:.38,delay:[1.7,2.5],sub:'קרקע וגגות מתערבבים'},6:{mix:Array(8).fill('normal').concat(Array(3).fill('fast'),Array(3).fill('heavy'),Array(2).fill('skilled')),active:5,roof:.45,delay:[1.5,2.3],sub:'הקרב נהיה קשה'},7:{mix:Array(9).fill('normal').concat(Array(4).fill('fast'),Array(4).fill('heavy'),Array(3).fill('skilled')),active:6,roof:.50,delay:[1.35,2.1],sub:'הרבה אויבים • RPG שימושי במיוחד'},8:{mix:Array(9).fill('normal').concat(Array(5).fill('fast'),Array(5).fill('heavy'),Array(4).fill('skilled')),active:6,roof:.53,delay:[1.28,2.0],sub:'לחץ מהרחוב ומהגגות'},9:{mix:Array(10).fill('normal').concat(Array(6).fill('fast'),Array(5).fill('heavy'),Array(5).fill('skilled')),active:7,roof:.56,delay:[1.2,1.9],sub:'מעט זמן לנוח'},10:{mix:Array(10).fill('normal').concat(Array(7).fill('fast'),Array(7).fill('heavy'),Array(6).fill('skilled')),active:7,roof:.58,delay:[1.15,1.8],sub:'השלב האחרון'}};
const ET={normal:{hp:3,speed:58,fire:[2.2,3.4],dmg:20,score:100,coin:10,w:38,h:58},fast:{hp:2,speed:82,fire:[1.6,2.6],dmg:16,score:150,coin:10,w:36,h:54},heavy:{hp:5,speed:40,fire:[2.5,3.8],dmg:28,score:200,coin:20,w:46,h:66},skilled:{hp:3,speed:63,fire:[1.65,2.55],dmg:20,score:175,coin:15,w:38,h:58}};
const WEAP={basic:{cool:.46,speed:700,dmg:1},mg:{cool:.46/3,speed:700,dmg:1},rpg:{cool:1.25,speed:310,dmg:99,rpg:true,radius:110}};
const p={x:125,y:0,w:42,h:70,vx:0,vy:0,speed:240,jump:625,grounded:true,crouch:false,facing:1,hp:100,maxHp:100,inv:0,lastShot:-99,hit:0};
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');toastT=1.15}function hud(){ui.score.textContent=score;ui.stage.textContent='STAGE '+stage;ui.rem.textContent=Math.max(0,stages[stage].mix.length-defeated)+' נשארו';ui.coins.textContent=save.coins;ui.shopCoins.textContent=save.coins}
function buildWorld(){roofs=[];stairs=[];doors=[];spawnPoints=[];buildings=[];const sec=630;for(let i=0;i<20;i++){const base=i*sec;const ry=ground-(175+(i%3)*34);const rx=base+245+(i%2)*20;const rw=255+(i%2)*35;const b={x:rx,y:ry,w:rw,h:ground-ry,variant:i%4};buildings.push(b);roofs.push({x:rx,y:ry,w:rw});const dx=base+74+(i%2)*62;doors.push({x:dx,y:ground-88,w:58,h:88,state:'closed',t:0});spawnPoints.push({type:'ground',x:dx+34,y:ground,door:i});spawnPoints.push({type:'roof',x:rx+rw*.56,y:ry,roof:i});const sw=155;if(i%2===0)stairs.push({x:rx-sw,y0:ground,y1:ry,w:sw,dir:1,roof:i});else stairs.push({x:rx+rw,y0:ry,y1:ground,w:sw,dir:-1,roof:i});}}
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);ground=H*.77;buildWorld();p.y=Math.min(p.y||ground-p.h,ground-p.h);drawPortraits()}
function cleanAtlas(){const oc=document.createElement('canvas');oc.width=atlas.naturalWidth;oc.height=atlas.naturalHeight;const q=oc.getContext('2d',{willReadFrequently:true});q.drawImage(atlas,0,0);const im=q.getImageData(0,0,oc.width,oc.height),d=im.data,W0=oc.width;for(let row=0;row<2;row++)for(let col=0;col<6;col++){const x0=col*CELL,y0=row*CELL,x1=x0+CELL,y1=y0+CELL,Q=[],seen=new Uint8Array(CELL*CELL);const bg=(x,y)=>{const i=(y*W0+x)*4,r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];return a<20||(Math.max(r,g,b)-Math.min(r,g,b)<14&&(r+g+b)/3>215)};for(let x=x0;x<x1;x++){Q.push([x,y0],[x,y1-1])}for(let y=y0;y<y1;y++){Q.push([x0,y],[x1-1,y])}while(Q.length){const [x,y]=Q.pop();if(x<x0||x>=x1||y<y0||y>=y1)continue;const si=(y-y0)*CELL+(x-x0);if(seen[si]||!bg(x,y))continue;seen[si]=1;d[(y*W0+x)*4+3]=0;Q.push([x+1,y],[x-1,y],[x,y+1],[x,y-1])}}q.putImageData(im,0,0);spriteSource=oc}function drawPortraits(){if(!atlas.complete||!atlas.naturalWidth)return;document.querySelectorAll('canvas.portrait').forEach(cv=>{const q=cv.getContext('2d'),row=+cv.dataset.row;q.clearRect(0,0,74,74);q.imageSmoothingEnabled=true;q.drawImage(spriteSource,0,row*CELL,CELL,CELL,-1,-1,76,76)})}atlas.onload=()=>{cleanAtlas();drawPortraits()};
let joyId=null,jx=0,jy=0,jumpLock=false;
function joyPos(e){const r=ui.joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy),lim=r.width*.34,k=m>lim?lim/m:1;jx=dx*k/lim;jy=dy*k/lim;ui.knob.style.transform=`translate(calc(-50% + ${dx*k}px),calc(-50% + ${dy*k}px))`}
ui.joy.addEventListener('pointerdown',e=>{joyId=e.pointerId;ui.joy.setPointerCapture(e.pointerId);joyPos(e);e.preventDefault()},{passive:false});ui.joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joyPos(e);e.preventDefault()},{passive:false});function joyUp(e){if(e.pointerId===joyId){joyId=null;jx=jy=0;ui.knob.style.transform='translate(-50%,-50%)';jumpLock=false}e.preventDefault()}ui.joy.addEventListener('pointerup',joyUp,{passive:false});ui.joy.addEventListener('pointercancel',joyUp,{passive:false});ui.fire.addEventListener('pointerdown',e=>{fire();e.preventDefault()},{passive:false});
function terrainY(cx,prevBottom,nextBottom){let best=ground;for(const roof of roofs){if(cx>roof.x&&cx<roof.x+roof.w&&prevBottom<=roof.y+16&&nextBottom>=roof.y-4)best=Math.min(best,roof.y)}for(const s of stairs){if(cx>=s.x&&cx<=s.x+s.w){const t=(cx-s.x)/s.w,sy=s.y0+(s.y1-s.y0)*t;if(Math.abs(nextBottom-sy)<72||p.grounded)best=Math.min(best,sy)}}return best}
function controls(){p.vx=0;p.crouch=false;if(Math.abs(jx)<.14&&Math.abs(jy)<.14){jumpLock=false;return}if(Math.abs(jy)>Math.abs(jx)*1.1){if(jy<-.36){if(p.grounded&&!jumpLock){p.vy=-p.jump;p.grounded=false;jumpLock=true}}else if(jy>.34){p.crouch=true;jumpLock=false}}else{if(jx>.18){p.vx=p.speed;p.facing=1}else if(jx<-.18){p.vx=-p.speed;p.facing=-1}jumpLock=false}}
function shotY(obj,level){if(level==='low')return obj.y+obj.h*.72;if(level==='high')return obj.y+obj.h*.23;return obj.y+obj.h*.46}function playerLevel(){return !p.grounded?'high':p.crouch?'low':'mid'}
function fire(){if(paused||!started)return;const w=WEAP[save.equipped]||WEAP.basic;if(clock-p.lastShot<w.cool)return;p.lastShot=clock;const y=shotY(p,playerLevel());bullets.push({x:p.x+p.w/2+p.facing*28,y,vx:p.facing*w.speed,life:w.rpg?2.5:1.6,dmg:w.dmg,rpg:!!w.rpg,radius:w.radius||0})}
function chooseSpawn(){const visible=spawnPoints.filter(sp=>sp.x>cam+W*.72&&sp.x<cam+W+420&&Math.abs(sp.x-p.x)>190);const all=visible.length?visible:spawnPoints.filter(sp=>sp.x>p.x+220&&sp.x<p.x+850);if(!all.length)return null;const sd=stages[stage];let pool=all.filter(sp=>sp.type==='roof'?(Math.random()<sd.roof):true);if(!pool.length)pool=all;return pool[Math.floor(Math.random()*pool.length)]}
function chooseType(){const remaining=stages[stage].mix.slice();const used={};for(const e of enemies)if(e.state!=='gone')used[e.type]=(used[e.type]||0)+1;for(let i=0;i<spawned;i++){const t=stages[stage].mix[i];used[t]=(used[t]||0)+0}return remaining[Math.min(spawned,remaining.length-1)]||'normal'}
function spawnEnemy(){const sd=stages[stage];if(spawned>=sd.mix.length)return;if(enemies.filter(e=>e.state!=='gone').length>=sd.active)return;const sp=chooseSpawn();if(!sp)return;const type=sd.mix[spawned],q=ET[type],roof=sp.type==='roof';enemies.push({type,x:sp.x,y:(roof?sp.y:ground)-q.h,w:q.w,h:q.h,hp:q.hp,maxHp:q.hp,dir:sp.x>p.x?-1:1,state:'enter',stateT:.42,roof,platformY:roof?sp.y:ground,fireT:rand(q.fire[0],q.fire[1]),teleT:0,shotLevel:'mid',inv:0,hit:0,knock:0,downT:0});spawned++;if(!roof&&sp.door!=null){doors[sp.door].state='opening';doors[sp.door].t=.45}spawnTimer=rand(sd.delay[0],sd.delay[1]);hud()}
function enemyShotLevel(e){const desired=playerLevel();if(e.type==='skilled')return Math.random()<.72?desired:['low','mid','high'][Math.floor(Math.random()*3)];return Math.random()<.58?desired:['low','mid','high'][Math.floor(Math.random()*3)]}
function enemyFire(e){const q=ET[e.type],y=shotY(e,e.shotLevel),dx=p.x-e.x,dir=dx>=0?1:-1;enemyBullets.push({x:e.x+e.w/2+dir*24,y,vx:dir*(e.type==='fast'?490:430),life:2.2,dmg:q.dmg,level:e.shotLevel})}
function hitEnemy(e,dmg,dir){if(e.inv>0||e.state==='down'||e.state==='fall'||e.state==='gone')return;e.hp-=dmg;e.inv=.18;e.hit=.18;e.knock=dir*(e.type==='heavy'?22:40);fx.push({kind:'spark',x:e.x+e.w/2,y:e.y+e.h*.45,t:.28});if(e.hp<=0){e.hp=0;e.state='fall';e.stateT=.35;e.downT=1.45;e.knock=dir*(e.type==='heavy'?30:55);score+=ET[e.type].score;defeated++;drops.push({x:e.x+e.w/2,y:e.y+e.h*.5,vy:-120,value:ET[e.type].coin,t:7});hud();if(defeated>=stages[stage].mix.length)stageClear()}else{e.state='hit';e.stateT=.18}}
function explode(b){fx.push({kind:'blast',x:b.x,y:b.y,t:.62,rad:b.radius});shake=.26;for(const e of enemies){if(e.state==='gone'||e.state==='down')continue;const d=Math.hypot((e.x+e.w/2)-b.x,(e.y+e.h/2)-b.y);if(d<=b.radius)hitEnemy(e,99,Math.sign((e.x+e.w/2)-b.x)||1)}}
function updatePlayer(d){controls();p.inv=Math.max(0,p.inv-d);p.hit=Math.max(0,p.hit-d);const prev=p.y+p.h;p.x=clamp(p.x+p.vx*d,0,WORLD-p.w);p.vy+=GRAV*d;p.y+=p.vy*d;const next=p.y+p.h,ty=terrainY(p.x+p.w/2,prev,next);p.grounded=false;if(p.vy>=0&&prev<=ty+16&&next>=ty){p.y=ty-p.h;p.vy=0;p.grounded=true}if(p.y+p.h>=ground){p.y=ground-p.h;p.vy=0;p.grounded=true}const target=clamp(p.x-W*.30,0,WORLD-W);cam+=(target-cam)*Math.min(1,d*7)}
function updateEnemies(d){for(const e of enemies){const q=ET[e.type];e.inv=Math.max(0,e.inv-d);e.hit=Math.max(0,e.hit-d);if(e.state==='gone')continue;if(e.state==='enter'){e.stateT-=d;if(e.stateT<=0)e.state='walk';continue}if(e.state==='hit'){e.x+=e.knock*d;e.stateT-=d;if(e.stateT<=0)e.state='walk';continue}if(e.state==='fall'){e.x+=e.knock*d;e.stateT-=d;if(e.stateT<=0)e.state='down';continue}if(e.state==='down'){e.downT-=d;if(e.downT<=0)e.state='gone';continue}const dx=p.x-e.x,eDir=dx>=0?1:-1;e.dir=eDir;const dist=Math.abs(dx);if(dist>190)e.x+=eDir*q.speed*d*(e.roof?.72:1);if(e.roof){const roof=roofs.find(z=>Math.abs(z.y-e.platformY)<3&&e.x>z.x-50&&e.x<z.x+z.w+50);if(roof)e.x=clamp(e.x,roof.x+10,roof.x+roof.w-e.w-10);e.y=e.platformY-e.h}else e.y=ground-e.h;e.fireT-=d;if(e.state==='tele'){e.teleT-=d;if(e.teleT<=0){enemyFire(e);e.state='walk';e.fireT=rand(q.fire[0],q.fire[1])}}else if(e.fireT<=0&&dist<560){e.shotLevel=enemyShotLevel(e);e.state='tele';e.teleT=.52}}}
function updateProjectiles(d){for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*d;b.life-=d;let remove=b.life<=0;if(!remove){for(const e of enemies){if(e.state==='gone'||e.state==='down')continue;if(b.x>e.x&&b.x<e.x+e.w&&b.y>e.y&&b.y<e.y+e.h){if(b.rpg)explode(b);else hitEnemy(e,b.dmg,Math.sign(b.vx));remove=true;break}}}if(remove)bullets.splice(i,1)}for(let i=enemyBullets.length-1;i>=0;i--){const b=enemyBullets[i];b.x+=b.vx*d;b.life-=d;let remove=b.life<=0;if(!remove&&p.inv<=0&&b.x>p.x&&b.x<p.x+p.w&&b.y>p.y+(p.crouch?p.h*.42:0)&&b.y<p.y+p.h){p.hp=Math.max(0,p.hp-b.dmg);p.inv=.78;p.hit=.24;shake=.18;remove=true;if(p.hp<=0)gameOver()}if(remove)enemyBullets.splice(i,1)}}
function updateDrops(d){for(let i=drops.length-1;i>=0;i--){const a=drops[i];a.vy+=650*d;a.y+=a.vy*d;if(a.y>ground-10){a.y=ground-10;a.vy*=-.25}a.t-=d;if(Math.abs(a.x-(p.x+p.w/2))<30&&Math.abs(a.y-(p.y+p.h/2))<55){save.coins+=a.value;persist();hud();toast('+'+a.value+' 🪙');drops.splice(i,1);continue}if(a.t<=0)drops.splice(i,1)}}
function updateFx(d){for(let i=fx.length-1;i>=0;i--){fx[i].t-=d;if(fx[i].t<=0)fx.splice(i,1)}shake=Math.max(0,shake-d)}function updateDoors(d){for(const door of doors){if(door.state==='opening'){door.t-=d;if(door.t<=0){door.state='open';door.t=.7}}else if(door.state==='open'){door.t-=d;if(door.t<=0){door.state='closing';door.t=.42}}else if(door.state==='closing'){door.t-=d;if(door.t<=0)door.state='closed'}}}
function stageClear(){if(stageChanging)return;stageChanging=true;paused=true;enemyBullets.length=0;setTimeout(()=>{if(stage>=10){save.highScore=Math.max(save.highScore,score);persist();$('winScore').textContent=score;ui.win.classList.add('show');return}stage++;ui.stageTitle.textContent='STAGE '+stage;ui.stageSub.textContent=stages[stage].sub;ui.stageCard.classList.add('show');setTimeout(()=>{ui.stageCard.classList.remove('show');resetStage(false);paused=false;stageChanging=false},1650)},450)}
function resetStage(full){enemies.length=bullets.length=enemyBullets.length=drops.length=fx.length=0;spawned=defeated=0;spawnTimer=1.2;if(full){stage=1;score=0;p.hp=p.maxHp;p.x=125;p.y=ground-p.h;p.vx=p.vy=0;cam=0}hud()}function gameOver(){paused=true;save.highScore=Math.max(save.highScore,score);persist();$('goScore').textContent=score;$('goStage').textContent=stage;$('goHigh').textContent=save.highScore;ui.over.classList.add('show')}
