'use strict';
(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});
const $=id=>document.getElementById(id),ui={score:$('score'),stage:$('stage'),left:$('left'),coins:$('coins'),message:$('message'),loading:$('loading'),joy:$('joy'),knob:$('knob'),fire:$('fire')};
const DPR=Math.min(2,devicePixelRatio||1);let W=0,H=0,ground=0,last=0,cam=0,clock=0,stage=1,score=0,coins=0,paused=false;
const LENGTH=[0,2300,2900,3550,4250,5000,5850,6750,7700,8750,9900],CLEAR=320;
const keys={x:0,jump:false,fire:false};const bullets=[],enemyBullets=[],enemies=[],obstacles=[],fx=[];
let playerSheet=null,playerCell=90;
const p={x:165,y:0,w:34,h:68,vx:0,vy:0,dir:1,onGround:true,hp:100,shot:0,inv:0,exit:false};
let entry={x:90,w:62,h:104},exit={x:2200,w:62,h:104,open:false};
function resize(){const r=canvas.getBoundingClientRect();W=Math.max(320,r.width);H=Math.max(560,r.height);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);ground=H-210;p.y=Math.min(p.y||ground-p.h,ground-p.h)}
addEventListener('resize',resize,{passive:true});resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function rnd(a,b){return a+Math.random()*(b-a)}
function toast(t){ui.message.textContent=t;ui.message.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.message.classList.remove('show'),1450)}
async function decodeMale(){try{if(!window.JF_MALE)return;const m=JF_MALE,raw=Uint8Array.from(atob(m.data),c=>c.charCodeAt(0));const ds=new DecompressionStream('deflate');const buf=await new Response(new Blob([raw]).stream().pipeThrough(ds)).arrayBuffer();const px=new Uint8Array(buf);if(px.length<m.w*m.h)return;const cv=document.createElement('canvas');cv.width=m.w;cv.height=m.h;const q=cv.getContext('2d'),im=q.createImageData(m.w,m.h);for(let i=0;i<m.w*m.h;i++){const pi=px[i],o=i*4;if(pi>=m.palette.length){im.data[o+3]=0;continue}const c=m.palette[pi];im.data[o]=c[0];im.data[o+1]=c[1];im.data[o+2]=c[2];im.data[o+3]=pi===m.palette.length-1?0:255}q.putImageData(im,0,0);playerSheet=cv;playerCell=m.cell||Math.floor(m.w/6)}catch(e){console.warn('V2 sprite decode fallback',e)}}
function resetStage(){const len=LENGTH[stage]||LENGTH[10];entry={x:82,w:64,h:108};exit={x:len-110,w:64,h:108,open:false};p.x=entry.x+entry.w+26;p.y=ground-p.h;p.vx=p.vy=0;p.hp=100;p.exit=false;cam=0;bullets.length=enemyBullets.length=enemies.length=obstacles.length=fx.length=0;const count=4+stage;for(let i=0;i<count;i++){const min=entry.x+CLEAR+220,max=exit.x-CLEAR-180,x=min+(max-min)*(i+1)/(count+1)+rnd(-80,80);enemies.push({x,y:ground-61,w:32,h:61,hp:2+Math.floor(stage/4),dir:-1,shot:rnd(.6,1.8),kind:i%3,dead:false})}for(let x=entry.x+CLEAR+220;x<exit.x-CLEAR-120;x+=rnd(430,620)){const n=Math.random();obstacles.push({x:x+rnd(80,180),w:n<.55?48:38,h:n<.55?46:40,type:n<.55?'crate':n<.82?'barrel':'rocks'})}updateHud();toast('STAGE '+stage+' • צא מהדלת והתקדם')}
function updateHud(){ui.score.textContent=score;ui.stage.textContent='STAGE '+stage;ui.left.textContent=enemies.filter(e=>!e.dead).length+' נשארו';ui.coins.textContent=coins}
function rectHit(a,b){return a.x<a.x+b.w&&false}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function shoot(){if(p.shot>0)return;p.shot=.22;bullets.push({x:p.x+(p.dir>0?p.w+5:-5),y:p.y+29,vx:p.dir*620,w:12,h:4});fx.push({x:p.x+(p.dir>0?p.w+9:-4),y:p.y+30,t:.09})}
function update(dt){clock+=dt;p.shot=Math.max(0,p.shot-dt);p.inv=Math.max(0,p.inv-dt);if(keys.fire)shoot();p.vx=keys.x*205;if(keys.x)p.dir=Math.sign(keys.x);if(keys.jump&&p.onGround){p.vy=-480;p.onGround=false;keys.jump=false}p.vy+=1120*dt;const oldX=p.x;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.y>=ground-p.h){p.y=ground-p.h;p.vy=0;p.onGround=true}else p.onGround=false;
for(const o of obstacles){const r={x:o.x,y:ground-o.h,w:o.w,h:o.h};if(overlap(p,r)&&p.y+p.h>r.y+8){p.x=oldX;p.vx=0}}
p.x=clamp(p.x,entry.x+entry.w+8,exit.x+40);
for(const b of bullets)b.x+=b.vx*dt;for(const b of enemyBullets)b.x+=b.vx*dt;
for(const e of enemies){if(e.dead)continue;e.dir=p.x<e.x?-1:1;const dist=Math.abs(p.x-e.x);if(dist>155&&dist<500)e.x+=e.dir*(54+stage*2)*dt;e.shot-=dt;if(dist<430&&e.shot<=0){e.shot=rnd(1.25,2.2);enemyBullets.push({x:e.x+e.w/2,y:e.y+26,vx:e.dir*270,w:9,h:4})}}
for(const b of bullets){for(const e of enemies){if(e.dead)continue;if(overlap(b,e)){b.dead=true;e.hp--;fx.push({x:b.x,y:b.y,t:.16});if(e.hp<=0){e.dead=true;score+=100;coins+=10}}}}
for(const b of enemyBullets){if(!b.dead&&p.inv<=0&&overlap(b,p)){b.dead=true;p.hp-=12;p.inv=.65;if(p.hp<=0){p.hp=100;p.x=entry.x+entry.w+26;p.y=ground-p.h;toast('נסה שוב')}}}
for(let i=bullets.length-1;i>=0;i--)if(bullets[i].dead||Math.abs(bullets[i].x-p.x)>900)bullets.splice(i,1);for(let i=enemyBullets.length-1;i>=0;i--)if(enemyBullets[i].dead||Math.abs(enemyBullets[i].x-p.x)>900)enemyBullets.splice(i,1);for(let i=fx.length-1;i>=0;i--){fx[i].t-=dt;if(fx[i].t<=0)fx.splice(i,1)}
if(!exit.open&&enemies.every(e=>e.dead)){exit.open=true;toast('הדרך נקייה • דלת היציאה נפתחה')}if(exit.open&&p.x+p.w>exit.x+10){if(stage<10){stage++;resetStage()}else toast('VICTORY')}
const target=clamp(p.x-W*.34,0,Math.max(0,exit.x+180-W));cam+=(target-cam)*Math.min(1,dt*6);updateHud()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,ground);g.addColorStop(0,'#54abe1');g.addColorStop(.5,'#b6dce5');g.addColorStop(1,'#ead4a8');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const art=window.JF_ART;if(art&&art.bgReady){const im=art.bg,dh=Math.min(H*.55,480),dw=dh*(im.naturalWidth/im.naturalHeight),shift=(cam*.06)%dw;ctx.save();ctx.globalAlpha=.82;for(let x=-shift-dw;x<W+dw;x+=dw)ctx.drawImage(im,x,ground-dh+34,dw,dh);ctx.restore()}else{ctx.fillStyle='rgba(75,105,98,.18)';for(let i=0;i<10;i++){const x=i*85-(cam*.04)%85;ctx.beginPath();ctx.moveTo(x,ground-70);ctx.lineTo(x+10,ground-210-(i%3)*35);ctx.lineTo(x+20,ground-70);ctx.fill()}}}
function stoneRect(x,y,w,h){ctx.fillStyle='#c9a96e';ctx.fillRect(x,y,w,h);ctx.strokeStyle='rgba(83,58,31,.30)';const bw=52,bh=24;for(let r=0,yy=y;yy<y+h;r++,yy+=bh)for(let xx=x-(r%2?26:0);xx<x+w;xx+=bw)ctx.strokeRect(xx+.5,yy+.5,bw,bh)}
function door(d,label){const y=ground-d.h;ctx.fillStyle='#d0b174';ctx.beginPath();ctx.arc(d.x+d.w/2,y+27,d.w/2+8,Math.PI,0);ctx.fill();ctx.fillRect(d.x-8,y+27,d.w+16,d.h-27);ctx.fillStyle='#171411';ctx.beginPath();ctx.arc(d.x+d.w/2,y+28,d.w/2-5,Math.PI,0);ctx.fill();ctx.fillRect(d.x+5,y+28,d.w-10,d.h-28);ctx.fillStyle=d.open?'#1b1713':'#54331f';ctx.fillRect(d.x+6,y+30,d.open?8:d.w-12,d.h-30);ctx.fillStyle='rgba(19,25,25,.92)';ctx.fillRect(d.x-8,y-28,d.w+16,22);ctx.fillStyle=d.open?'#ffe98d':'#f2dfb0';ctx.font='800 12px Arial';ctx.textAlign='center';ctx.fillText(label,d.x+d.w/2,y-12);if(d.open){const gr=ctx.createRadialGradient(d.x+d.w/2,y+55,2,d.x+d.w/2,y+55,78);gr.addColorStop(0,'rgba(255,218,99,.28)');gr.addColorStop(1,'rgba(255,218,99,0)');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(d.x+d.w/2,y+55,78,0,Math.PI*2);ctx.fill()}}
function drawWorld(){stoneRect(0,ground,exit.x+350,160);for(let x=480;x<exit.x-300;x+=520){const h=170+(Math.floor(x/520)%3)*38;stoneRect(x,ground-h,310,h);ctx.fillStyle='#3e3932';for(let i=0;i<3;i++){const wx=x+38+i*82,wy=ground-h+52;ctx.beginPath();ctx.roundRect(wx,wy,38,58,5);ctx.fill();ctx.fillStyle='#7eb0c2';ctx.fillRect(wx+6,wy+7,26,43);ctx.fillStyle='#3e3932'}if((x/520)%2<1){ctx.fillStyle='#47683d';ctx.beginPath();ctx.arc(x+275,ground-h-4,27,Math.PI,0);ctx.fill()}}door(entry,'התחלה');door(exit,exit.open?'יציאה':'נעול');for(const o of obstacles)drawObstacle(o)}
function drawObstacle(o){const y=ground-o.h;if(o.type==='crate'){ctx.fillStyle='#76502e';ctx.fillRect(o.x,y,o.w,o.h);ctx.strokeStyle='#39271a';ctx.lineWidth=3;ctx.strokeRect(o.x+1,y+1,o.w-2,o.h-2);ctx.beginPath();ctx.moveTo(o.x+4,y+4);ctx.lineTo(o.x+o.w-4,y+o.h-4);ctx.moveTo(o.x+o.w-4,y+4);ctx.lineTo(o.x+4,y+o.h-4);ctx.stroke()}else if(o.type==='barrel'){ctx.fillStyle='#695f4e';ctx.beginPath();ctx.roundRect(o.x,y,o.w,o.h,6);ctx.fill();ctx.fillStyle='#2c2c29';ctx.fillRect(o.x,y+8,o.w,4);ctx.fillRect(o.x,y+o.h-11,o.w,4)}else{ctx.fillStyle='#7f7463';for(let i=0;i<4;i++){ctx.beginPath();ctx.arc(o.x+8+i*9,y+o.h-8-(i%2)*7,11,0,Math.PI*2);ctx.fill()}}}
function drawPlayerFallback(x,y,dir){ctx.save();ctx.translate(x+p.w/2,y+p.h);ctx.scale(dir,1);ctx.fillStyle='#253444';ctx.fillRect(-9,-28,8,27);ctx.fillRect(3,-28,8,27);ctx.fillStyle='#3a2b20';ctx.fillRect(-12,-5,12,5);ctx.fillRect(2,-5,12,5);ctx.fillStyle='#f3f2ec';ctx.fillRect(-14,-57,28,28);ctx.fillStyle='#326da3';ctx.fillRect(-10,-52,20,25);ctx.fillStyle='#c58c62';ctx.fillRect(-9,-71,18,15);ctx.fillStyle='#f2f2ed';ctx.fillRect(-11,-76,22,8);ctx.fillStyle='#2d6fb2';ctx.fillRect(-4,-76,8,8);ctx.fillStyle='#15191a';ctx.fillRect(12,-48,42,6);ctx.fillRect(46,-51,11,11);ctx.restore()}
function drawPlayer(){const x=p.x,y=p.y;if(p.inv>0&&Math.floor(p.inv*16)%2)return;ctx.fillStyle='rgba(0,0,0,.2)';ctx.beginPath();ctx.ellipse(x+p.w/2,y+p.h+4,18,4,0,0,Math.PI*2);ctx.fill();if(playerSheet){let col=0;if(p.shot>.08)col=4;else if(!p.onGround)col=3;else if(Math.abs(p.vx)>4)col=Math.floor(clock*10)%2?2:1;const sw=playerCell,sh=playerSheet.height,dh=92,dw=dh*(sw/sh);ctx.save();ctx.imageSmoothingEnabled=false;if(p.dir<0){ctx.translate(x+p.w/2+dw/2,0);ctx.scale(-1,1);ctx.drawImage(playerSheet,col*sw,0,sw,sh,0,y+p.h-dh,dw,dh)}else ctx.drawImage(playerSheet,col*sw,0,sw,sh,x+p.w/2-dw/2,y+p.h-dh,dw,dh);ctx.restore()}else drawPlayerFallback(x,y,p.dir);ctx.fillStyle='rgba(16,22,24,.75)';ctx.fillRect(x-3,y-10,p.w+6,5);ctx.fillStyle='#62d66c';ctx.fillRect(x-2,y-9,(p.w+4)*p.hp/100,3)}
function drawEnemy(e){if(e.dead)return;ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(e.x+e.w/2,e.y+e.h+3,15,3,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h);ctx.scale(e.dir,1);ctx.fillStyle=e.kind===0?'#53603d':e.kind===1?'#222b34':'#4d5147';ctx.fillRect(-13,-48,26,28);ctx.fillStyle=e.kind===0?'#b54035':e.kind===1?'#171d24':'#403b35';ctx.fillRect(-11,-66,22,17);ctx.fillStyle='#c69068';ctx.fillRect(-6,-59,12,5);ctx.fillStyle='#13181b';ctx.fillRect(12,-43,39,6);ctx.fillRect(44,-47,11,13);ctx.fillStyle='#27303a';ctx.fillRect(-9,-22,7,22);ctx.fillRect(3,-22,7,22);ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);drawSky();ctx.save();ctx.translate(-cam,0);drawWorld();for(const e of enemies)drawEnemy(e);ctx.fillStyle='#f4de75';for(const b of bullets)ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#f37b58';for(const b of enemyBullets)ctx.fillRect(b.x,b.y,b.w,b.h);for(const f of fx){ctx.fillStyle='rgba(255,211,83,'+clamp(f.t/.16,0,1)+')';ctx.beginPath();ctx.arc(f.x,f.y,9,0,Math.PI*2);ctx.fill()}drawPlayer();ctx.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(!paused)update(dt);render();requestAnimationFrame(loop)}
function joyPoint(ev){const r=ui.joy.getBoundingClientRect(),x=ev.clientX-(r.left+r.width/2),y=ev.clientY-(r.top+r.height/2),m=Math.hypot(x,y),lim=45,k=m>lim?lim/m:1;ui.knob.style.transform=`translate(${x*k}px,${y*k}px)`;keys.x=Math.abs(x)>12?clamp(x/45,-1,1):0;if(y<-35)keys.jump=true}
let joyId=null;ui.joy.addEventListener('pointerdown',e=>{joyId=e.pointerId;ui.joy.setPointerCapture(joyId);joyPoint(e)});ui.joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joyPoint(e)});function endJoy(e){if(e.pointerId!==joyId)return;joyId=null;keys.x=0;ui.knob.style.transform='translate(0,0)'}ui.joy.addEventListener('pointerup',endJoy);ui.joy.addEventListener('pointercancel',endJoy);ui.fire.addEventListener('pointerdown',e=>{ui.fire.setPointerCapture(e.pointerId);keys.fire=true;shoot()});ui.fire.addEventListener('pointerup',()=>keys.fire=false);ui.fire.addEventListener('pointercancel',()=>keys.fire=false);
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.x=-1;if(e.key==='ArrowRight'||e.key==='d')keys.x=1;if(e.key==='ArrowUp'||e.key==='w'||e.key===' ')keys.jump=true;if(e.key==='f')keys.fire=true});addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight','a','d'].includes(e.key))keys.x=0;if(e.key==='f')keys.fire=false});
(async()=>{await decodeMale();resetStage();ui.loading.classList.add('done');requestAnimationFrame(loop)})();
})();