(()=>{let root=null,garageTab='ship',board='career_score',leaderRows=null,leaderLoading=false,homeLaunching=false;
const tabNames={ship:'SHIPS',color:'COLORS',decal:'DECALS',shot:'WEAPON FX',background:'BACKGROUNDS',aura:'AURAS',ability:'ABILITIES'};
function money(){return`<div class="ns-wallet"><span class="coin">◉ ${EconomySystem.balance('coins')}</span><span class="gem">◆ ${EconomySystem.balance('gems')}</span></div>`}
function button(label,action,cls=''){return`<button class="ns-btn ${cls}" data-action="${action}">${label}</button>`}
function itemName(id=''){return id.split('.').slice(1).join(' ').replaceAll('_',' ').toUpperCase()||'UNKNOWN'}
function playerProgress(){const p=window.PlayerProgressionSystem?.snapshot?.()||{};const level=Number(p.playerLevel??p.level??1)||1;const current=Number(p.currentLevelXP??p.levelXP??0)||0;const needed=Math.max(1,Number(p.nextLevelXP??p.levelXPNeeded??900)||900);return{level,current,needed,pct:Math.max(0,Math.min(100,current/needed*100))}}
function rankText(){const r=RankSystem.snapshot?.()||{};if(r.label)return String(r.label).toUpperCase();if(r.name)return String(r.name).toUpperCase();return`RANK ${r.rank||1}`}function equippedShipAsset(){const loadout=CustomizationSystem.loadout?.()||{},shipKey=String(loadout.ship||'ship.nova').split('.').pop();const content=GameConfig.get('content')||{},ship=content.ships?.[shipKey]||content.ships?.starter,asset=content.assets?.[ship?.assetId];return asset?.src||'assets/ships/nova-normal.webp'}function icon(kind){const paths={garage:'M5 19V9l7-5 7 5v10h-5v-6h-4v6H5zm-2 2h18',objectives:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 4a6 6 0 1 1 0 12 6 6 0 0 1 0-12zm0 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6z',profile:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm-7 8c.5-4 3.1-6 7-6s6.5 2 7 6H5z',leaderboard:'M6 4h3v4H6V4zm9 0h3v7h-3V4zm-4 0h3v10h-3V4zM4 16h16v4H4v-4z'};return`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[kind]||paths.profile}"/></svg>`}
function shell(title,body,back='home'){return`<section class="ns-screen"><header><button class="ns-back" data-action="${back}">‹</button><h2>${title}</h2>${money()}</header>${body}</section>`}
function home(){
 const p=ProfileSystem.snapshot(),progress=playerProgress(),run=RunCommands.snapshot(),continuing=!!run?.active,shipSrc=equippedShipAsset();
 return`<section class="ns-screen ns-home">
   <div class="ns-home-art" aria-hidden="true"><span class="ns-home-nebula"></span><span class="ns-home-planet"></span><span class="ns-home-asteroids"></span><span class="ns-home-stars"></span></div>
   <header class="ns-home-top">
     <button class="ns-settings" aria-label="Settings" data-action="settings"><span>⚙</span></button>
     <button class="ns-player-status" data-action="profile" aria-label="Open player profile">
       <span class="ns-avatar-mini">◈</span>
       <span class="ns-player-copy"><strong>${p.displayName||'PILOT'}</strong><b>LV ${progress.level}</b><small>${rankText()}</small></span>
       <span class="ns-player-xp"><i style="width:${progress.pct}%"></i></span>
     </button>
     ${money()}
   </header>
   <div class="ns-brand" aria-label="Neon Survivor"><strong>NEON</strong><span>SURVIVOR</span></div>
   <div class="ns-hero">
      <div class="ns-orbit ns-orbit-a"></div><div class="ns-orbit ns-orbit-b"></div>
      <div class="ns-hero-glow"></div>
      <img class="ns-hero-ship" src="${shipSrc}" alt="Equipped ship">
      <div class="ns-engine engine-left"></div><div class="ns-engine engine-right"></div>
   </div>
   <div class="ns-primary">${button(continuing?'CONTINUE':'PLAY',continuing?'continue':'play','accent home-play')}</div>
   <nav class="ns-home-nav" aria-label="Main menu">
      <button data-action="garage"><span class="nav-icon">${icon('garage')}</span><b>GARAGE</b></button>
      <button data-action="objectives"><span class="nav-icon">${icon('objectives')}</span><b>OBJECTIVES</b></button>
      <button data-action="profile"><span class="nav-icon">${icon('profile')}</span><b>PROFILE</b></button>
      <button data-action="leaderboard"><span class="nav-icon">${icon('leaderboard')}</span><b>LEADERBOARD</b></button>
   </nav>
 </section>`
}
function garageCard(v){const p=v.acquisition?.price,locked=!v.owned&&!v.eligibility?.met;let action=v.equipped?'<span class="ns-equipped">EQUIPPED</span>':v.owned?button('EQUIP',`equip:${v.id}`,'mini'):v.acquisition?.type==='purchase'&&p?button(`${p.currency==='gems'?'◆':'◉'} ${p.amount}`,`buy:${v.id}`,v.affordable&&!locked?'mini':'mini disabled'):`<span class="ns-lock">${locked?'LOCKED':'REWARD'}</span>`;return`<article class="ns-item ${v.equipped?'selected':''}"><div class="ns-item-art">${v.type==='ship'?'▲':v.type==='color'?'●':v.type==='decal'?'✦':v.type==='shot'?'⌁':v.type==='background'?'▧':v.type==='aura'?'◌':'⚡'}</div><div><b>${itemName(v.id)}</b><small>${String(v.rarity||'common').toUpperCase()}</small></div>${action}</article>`}
function garage(){const loadout=CustomizationSystem.loadout(),cats=CustomizationSystem.categories(),items=CustomizationSystem.catalog(garageTab);return shell('GARAGE',`<div class="ns-garage-preview"><div class="ns-preview-aura"></div><div class="ns-garage-ship">▲</div><strong>${itemName(loadout.ship||'ship.nova')}</strong><small>CURRENT LOADOUT</small></div><nav class="ns-tabs">${cats.map(c=>`<button data-action="tab:${c}" class="${c===garageTab?'active':''}">${tabNames[c]||c.toUpperCase()}</button>`).join('')}</nav><div class="ns-items">${items.map(garageCard).join('')||'<p>No items yet.</p>'}</div>`)}
function modes(){return shell('SELECT MODE',`<div class="ns-mode-card"><b>SOLO RUN</b><p>Survive, upgrade your ship and climb the ranks.</p>${button('DEPLOY','solo','accent')}</div><div class="ns-mode-card locked"><b>CO-OP</b><p>Fight and progress together with friends.</p><span>ONLINE MODE — NEXT PHASE</span></div>`)}
function shop(){const offers=ShopSystem.offers();return shell('SHOP',`<div class="ns-section-title"><div><small>LIVE STORE</small><h3>FEATURED OFFERS</h3></div></div><div class="ns-offers">${offers.length?offers.map(o=>`<article class="ns-offer"><div class="ns-offer-art">${o.item?.type==='ability'?'⚡':'✦'}</div><div><b>${itemName(o.itemId)}</b><small>${String(o.item?.rarity||'special').toUpperCase()}</small></div>${o.item?.owned?'<span class="ns-equipped">OWNED</span>':button(`${o.price?.currency==='gems'?'◆':'◉'} ${o.price?.amount??'—'}`,`offer:${o.id}`,o.affordable&&o.eligible?'mini':'mini disabled')}</article>`).join(''):'<div class="ns-empty"><b>NO LIVE OFFERS</b><p>The store is ready for remotely configured offers.</p></div>'}</div>`)}
function stats(){const s=StatisticsSystem.snapshot(),cards=[['RUNS',s.runs],['KILLS',s.kills],['ELITES',s.eliteKills],['BOSSES',s.bossKills],['BEST SCORE',s.bestScore],['BEST LEVEL',s.bestLevel],['BEST DISTANCE',Math.round(s.bestDistance)],['PLAY TIME',`${Math.floor(s.totalPlaySeconds/60)}m`]];return shell('STATISTICS',`<div class="ns-stat-hero"><small>CAREER RANK</small><strong>${RankSystem.snapshot().rank||1}</strong></div><div class="ns-stat-grid">${cards.map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div>`)}
function results(){const a=AppFlowSystem.snapshot().results||{},r=a.run||RunCommands.snapshot()||{};return shell('RUN COMPLETE',`<div class="ns-results-hero"><small>FINAL SCORE</small><strong>${Math.round(r.score||0)}</strong><span>LEVEL ${r.level||1}</span></div><div class="ns-result-row"><div><small>TIME</small><b>${Math.floor((r.time||0)/60)}:${String(Math.floor((r.time||0)%60)).padStart(2,'0')}</b></div><div><small>DISTANCE</small><b>${Math.round(r.distance||0)}</b></div></div><div class="ns-results-actions">${button('PLAY AGAIN','replay','accent')}${button('GARAGE','garage')}${button('HOME','home')}</div>`)}
function profile(){const p=ProfileSystem.snapshot(),a=AccountSystem.snapshot();return shell('PROFILE',`<div class="ns-profile-hero"><div class="ns-avatar">◉</div><h3>${p.displayName}</h3><span>${rankText()}</span><small>${a.authenticated?`CONNECTED · ${String(a.provider).toUpperCase()}`:'GUEST ACCOUNT'}</small></div><div class="ns-profile-panel"><label>PILOT NAME</label><div class="ns-name-row"><input id="pilot-name" maxlength="18" value="${String(p.displayName).replaceAll('"','&quot;')}">${button('SAVE','save-name','mini')}</div><div class="ns-account-id"><small>PLAYER ID</small><code>${a.playerId}</code></div>${a.authenticated?button('SIGN OUT','signout'):'<p>Your progress is stored locally. Account providers can be connected when the authentication service goes live.</p>'}</div>`)}
function leaderboard(){const boards=LeaderboardSystem.boards(),online=LeaderboardSystem.available();let body;if(!online)body=`<div class="ns-empty"><b>LEADERBOARDS OFFLINE</b><p>Guest/local play is active. Rankings will appear here when an authenticated leaderboard provider is connected.</p></div>`;else if(leaderLoading)body='<div class="ns-empty"><b>LOADING…</b></div>';else body=`<div class="ns-leader-list">${(leaderRows||[]).map((e,i)=>`<div><span>#${e.rank||i+1}</span><b>${e.displayName||e.profile?.displayName||'PILOT'}</b><strong>${e.score||0}</strong></div>`).join('')||'<div class="ns-empty"><b>NO SCORES YET</b></div>'}</div>`;return shell('LEADERBOARD',`<nav class="ns-tabs">${Object.values(boards).map(b=>`<button data-action="board:${b}" class="${b===board?'active':''}">${b.replaceAll('_',' ').toUpperCase()}</button>`).join('')}</nav>${body}`)}
async function loadBoard(){if(!LeaderboardSystem.available()){leaderRows=[];render();return}leaderLoading=true;render();const r=await LeaderboardSystem.top(board,50);leaderRows=r.entries||[];leaderLoading=false;render()}
function launch(resume=false){if(homeLaunching)return;homeLaunching=true;const el=root.querySelector('.ns-home');el?.classList.add('is-launching');setTimeout(()=>{homeLaunching=false;if(resume&&AppFlowSystem.resume)AppFlowSystem.resume();else AppFlowSystem.play('solo')},760)}
function render(){if(!root)return;const state=AppFlowSystem.snapshot().state;if(state==='home')root.innerHTML=home();else if(state==='mode-select')root.innerHTML=modes();else if(state==='garage')root.innerHTML=garage();else if(state==='shop')root.innerHTML=shop();else if(state==='stats')root.innerHTML=stats();else if(state==='results')root.innerHTML=results();else if(state==='profile')root.innerHTML=profile();else if(state==='leaderboard')root.innerHTML=leaderboard();else if(state==='playing'){root.style.display='none';return}root.style.display='block'}
async function act(a){if(a==='home')AppFlowSystem.home();else if(a==='garage')AppFlowSystem.garage();else if(a==='shop')AppFlowSystem.shop();else if(a==='stats'||a==='objectives')AppFlowSystem.stats();else if(a==='profile')AppFlowSystem.profile();else if(a==='play')launch(false);else if(a==='continue')launch(true);else if(a==='solo')AppFlowSystem.play('solo');else if(a==='replay')AppFlowSystem.replay();else if(a==='settings')GameEvents.emit('ui:settings-requested',{source:'home'});else if(a==='leaderboard'){AppFlowSystem.leaderboard();loadBoard()}else if(a==='save-name'){const v=root.querySelector('#pilot-name')?.value.trim();if(v)await ProfileSystem.update({displayName:v.slice(0,18)})}else if(a==='signout')await AccountSystem.signOut();else if(a.startsWith('board:')){board=a.slice(6);loadBoard()}else if(a.startsWith('tab:'))garageTab=a.slice(4);else if(a.startsWith('equip:'))CustomizationSystem.equip(a.slice(6));else if(a.startsWith('buy:')){const id=a.slice(4),r=CustomizationSystem.purchase(id);if(r.purchased)CustomizationSystem.equip(id)}else if(a.startsWith('offer:'))ShopSystem.purchase(a.slice(6));render()}
const system={id:'app-shell',dependsOn:['app-flow','profile','account','economy','rank','customization','shop','statistics','leaderboards'],start(){root=document.createElement('div');root.id='app-shell';document.body.appendChild(root);root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.classList.contains('disabled'))act(b.dataset.action)});['app-flow:changed','economy:balance-changed','profile:updated','customization:changed','customization:purchased','shop:purchased','statistics:changed','account:signed-out','account:signed-in','progression:rank-progress','progression:rank-up'].forEach(n=>GameEvents.on(n,render));render()},render};
GameSystems.register(system);window.AppShell=system})();
