(()=>{let root;
function fmtTime(seconds=0){seconds=Math.max(0,Math.floor(seconds));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
function show(){const r=RunCommands.snapshot()||{};root.querySelector('[data-score]').textContent=Math.floor(r.score||0).toLocaleString();root.querySelector('[data-evolution]').textContent=r.level||1;root.querySelector('[data-time]').textContent=fmtTime(r.time||0);root.querySelector('[data-distance]').textContent=Math.round(r.distance||0).toLocaleString();root.classList.add('show')}
function hide(){root?.classList.remove('show')}
const system={id:'game-over-ui',dependsOn:['gameplay-lifecycle','run'],start(){const style=document.createElement('style');style.textContent=`
#game-over-screen{position:fixed;inset:0;z-index:100;display:none;place-items:center;padding:24px;background:radial-gradient(circle at 50% 34%,#28101899,#020611ee 58%);backdrop-filter:blur(12px);color:#fff;font-family:Inter,system-ui,-apple-system,sans-serif;pointer-events:auto}
#game-over-screen.show{display:grid}.game-over-card{width:min(390px,100%);text-align:center;padding:32px 24px 25px;border:1px solid #ff637044;border-radius:26px;background:#07101bea;box-shadow:0 28px 80px #000c,0 0 50px #ff405522}
.game-over-mark{font-size:34px;color:#ff6073;text-shadow:0 0 24px #ff4055}.game-over-card>small{display:block;margin-top:8px;color:#ff7c8b;font-size:10px;font-weight:900;letter-spacing:.24em}.game-over-card h1{margin:7px 0 22px;font-size:36px;letter-spacing:.08em}
.game-over-score small,.game-over-stat small{display:block;color:#91a7b8;font-size:9px;font-weight:900;letter-spacing:.14em}.game-over-score b{display:block;margin-top:4px;font-size:48px;line-height:1}.game-over-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:20px 0}.game-over-stat{padding:13px 6px;border-radius:13px;background:#ffffff09}.game-over-stat b{display:block;margin-top:5px;font-size:17px}
.game-over-actions{display:grid;gap:10px}.game-over-actions button{height:54px;border:1px solid #ffffff1b;border-radius:15px;background:#101d2b;color:#fff;font:900 13px Inter,system-ui;letter-spacing:.09em}.game-over-actions .restart{background:#d6a83d;border-color:#f1ca65;color:#080b10}
`;document.head.appendChild(style);root=document.createElement('div');root.id='game-over-screen';root.innerHTML='<section class="game-over-card"><div class="game-over-mark">✦</div><small>SHIP DESTROYED</small><h1>GAME OVER</h1><div class="game-over-score"><small>FINAL SCORE</small><b data-score>0</b></div><div class="game-over-stats"><div class="game-over-stat"><small>EVOLUTION</small><b>LV <span data-evolution>1</span></b></div><div class="game-over-stat"><small>TIME</small><b data-time>0:00</b></div><div class="game-over-stat"><small>DISTANCE</small><b data-distance>0</b></div></div><div class="game-over-actions"><button class="restart" data-game-over="restart">RESTART RUN</button><button data-game-over="home">RETURN HOME</button></div></section>';document.body.appendChild(root);root.addEventListener('click',e=>{const a=e.target.closest('[data-game-over]')?.dataset.gameOver;if(a==='restart'){hide();AppFlowSystem.replay()}else if(a==='home'){hide();AppFlowSystem.home()}});GameEvents.on('game:over',show);GameEvents.on('run:started',hide)}};GameSystems.register(system);window.GameOverUI=system})();